<a href="https://colab.research.google.com/github/yuroua20/fin_data/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "/content/損益表-累季.csv"

In [3]:
df = pd.read_csv(url, index_col=0)
df

,2731 雄獅,2739 寒舍,2731 雄獅.1,2739 寒舍.1,2731 雄獅.2,2739 寒舍.2,2731 雄獅.3,2739 寒舍.3,(單位:億元)
公司,,,,,,,,,
年/月,2023/12,2023/12,2023/09,2023/09,2023/06,2023/06,2023/03,2023/03,NaN
季別,4,4,3,3,2,2,1,1,NaN
合併(Y/N),Y,Y,Y,Y,Y,Y,Y,Y,NaN
月份,12,12,9,9,6,6,3,3,NaN
幣別,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NaN
營業收入,215.1,48.31,154.5,34.49,87.96,23.02,32.92,11.95,NaN
營業成本,182.7,29.66,131.3,21.86,74.36,14.35,27.09,7.38,NaN
營業毛利,32.41,18.65,23.22,12.63,13.6,8.67,5.82,4.57,NaN
營業毛利淨額,32.41,18.65,23.22,12.63,13.6,8.67,5.82,4.57,NaN
推銷費用,-,2.83,-,1.99,-,1.27,-,0.62,NaN
管理費用,-,11.21,-,8.15,-,5.33,-,2.59,NaN
營業費用,23.08,14.04,16.94,10.14,10.41,6.61,4.79,3.21,NaN
其他收益及費損合計,-,1.65,-,1.48,-,0.21,-,0.071,NaN
營業利益,9.34,6.26,6.28,3.96,3.19,2.27,1.04,1.44,NaN
利息收入,0.26,0.025,0.16,0.02,0.11,0.016,0.032,0.008,NaN
其他收入,0.5,0.32,0.31,0.24,0.22,0.15,0.092,0.07,NaN
其他利益及損失,5.27,-0.088,0.089,-0.014,0.059,-0.009,0.003,-0.005,NaN
財務成本,0.27,1.98,0.22,1.5,0.15,1.01,0.091,0.51,NaN
採用權益法認列之關聯企業及合資損益之份額,0.091,0.19,0,0.076,0,0.042,0,0.007,NaN
業外損益合計,5.85,-1.53,0.35,-1.18,0.23,-0.82,0.036,-0.43,NaN
稅前淨利,15.19,4.73,6.62,2.78,3.42,1.46,1.07,1,NaN
所得稅費用,0.84,0.59,0.48,0.25,0.11,0.25,0.078,0.19,NaN
繼續營業單位稅後損益,14.35,4.14,6.14,2.53,3.31,1.21,0.99,0.82,NaN
合併稅後淨利,14.35,4.14,6.14,2.53,3.31,1.21,0.99,0.82,NaN
歸屬於非控制權益之淨利,0.43,-,0.32,-,0.13,-,0.063,-,NaN
稅後淨利,13.92,4.14,5.82,2.53,3.18,1.21,0.93,0.82,NaN
確定福利計畫之再衡量數,-0.042,0.005,0.042,0,0.52,-,0.37,-,NaN
透過其他綜合損益按公允價值衡量之權益工具投資未實現評價損益,-0.3,-,0,0.55,0,0.079,0,0.027,NaN
採用權益法認列之關聯企業及合資之其他綜合損益之份額–不重分類至損益,0.009,0.53,0.042,0.55,0.52,0.079,0.37,0.027,NaN
與不重分類之項目相關之所得稅,-0.008,0.001,-0.022,-,-0.11,-,-0.009,-,NaN
不重分類至損益之項目合計,-0.33,0.53,-0.022,-,-0.11,-,-0.009,-,NaN
國外營運機構財務報表換算之兌換差額,-0.073,-,0.021,0.55,0.41,0.079,0.36,0.027,NaN
後續可能重分類至損益之項目合計,-0.073,-,6.16,3.08,3.72,1.29,1.35,0.85,NaN
其他綜合損益合計,-0.4,0.53,5.84,3.08,3.53,1.29,1.24,0.85,NaN
綜合損益,13.95,4.67,0.32,-,0.19,-,0.11,-,NaN
綜合損益–歸屬於母公司,13.52,4.67,6.4,2.76,3.54,1.32,1.08,0.9,NaN
綜合損益–歸屬於非控制權益,0.44,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
每股稅後盈餘(元),15.21,4.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head()

,2731 雄獅,2739 寒舍,2731 雄獅.1,2739 寒舍.1,2731 雄獅.2,2739 寒舍.2,2731 雄獅.3,2739 寒舍.3,(單位:億元)
公司,,,,,,,,,
年/月,2023/12,2023/12,2023/09,2023/09,2023/06,2023/06,2023/03,2023/03,NaN
季別,4,4,3,3,2,2,1,1,NaN
合併(Y/N),Y,Y,Y,Y,Y,Y,Y,Y,NaN
月份,12,12,9,9,6,6,3,3,NaN
幣別,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NaN

In [5]:
df.columns

Index(['2731 雄獅', '2739 寒舍', '2731 雄獅.1', '2739 寒舍.1', '2731 雄獅.2',
       '2739 寒舍.2', '2731 雄獅.3', '2739 寒舍.3', '(單位:億元)'],
      dtype='object')

In [6]:
url = "/content/資產負債表-累季.csv"

In [7]:
df = pd.read_csv(url, index_col=0)
df

,2731 雄獅,2739 寒舍,2731 雄獅.1,2739 寒舍.1,2731 雄獅.2,2739 寒舍.2,2731 雄獅.3,2739 寒舍.3,(單位:億元)
公司,,,,,,,,,
年/月,2023/12,2023/12,2023/09,2023/09,2023/06,2023/06,2023/03,2023/03,NaN
季別,4,4,3,3,2,2,1,1,NaN
合併(Y/N),Y,Y,Y,Y,Y,Y,Y,Y,NaN
月份,12,12,9,9,6,6,3,3,NaN
幣別,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NaN
...,...,...,...,...,...,...,...,...,...
股東權益總額,38.22,11.86,NaN,NaN,-,0,26.15,7.91,NaN
待註銷股本股數(萬張),-,0,NaN,NaN,28.79,8.35,NaN,NaN,NaN
預收股款之約當發行股數(萬張),0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
母公司暨子公司持有之母公司庫藏股股數(萬張),-,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
每股淨值(元),40,11.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.head()

,2731 雄獅,2739 寒舍,2731 雄獅.1,2739 寒舍.1,2731 雄獅.2,2739 寒舍.2,2731 雄獅.3,2739 寒舍.3,(單位:億元)
公司,,,,,,,,,
年/月,2023/12,2023/12,2023/09,2023/09,2023/06,2023/06,2023/03,2023/03,NaN
季別,4,4,3,3,2,2,1,1,NaN
合併(Y/N),Y,Y,Y,Y,Y,Y,Y,Y,NaN
月份,12,12,9,9,6,6,3,3,NaN
幣別,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NTD,NaN

In [9]:
df.columns

Index(['2731 雄獅', '2739 寒舍', '2731 雄獅.1', '2739 寒舍.1', '2731 雄獅.2',
       '2739 寒舍.2', '2731 雄獅.3', '2739 寒舍.3', '(單位:億元)'],
      dtype='object')